// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8oP5XHs4AR4DeN3gJdXinJpQ9d-i8Xnw',
    appId: '1:737126990757:web:7adb2bfa684fbc76421e4c',
    messagingSenderId: '737126990757',
    projectId: 'my-goal-mate',
    authDomain: 'my-goal-mate.firebaseapp.com',
    storageBucket: 'my-goal-mate.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2pXu2x3QS4rLxxIBjhuyyidQrUDrLG40',
    appId: '1:737126990757:android:dc13a9d339b6ef18421e4c',
    messagingSenderId: '737126990757',
    projectId: 'my-goal-mate',
    storageBucket: 'my-goal-mate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoMfhqp5pLQlBUsNleRLqXSqmonhPQQ24',
    appId: '1:737126990757:ios:6d37d627eda18254421e4c',
    messagingSenderId: '737126990757',
    projectId: 'my-goal-mate',
    storageBucket: 'my-goal-mate.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoMfhqp5pLQlBUsNleRLqXSqmonhPQQ24',
    appId: '1:737126990757:ios:6d37d627eda18254421e4c',
    messagingSenderId: '737126990757',
    projectId: 'my-goal-mate',
    storageBucket: 'my-goal-mate.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8oP5XHs4AR4DeN3gJdXinJpQ9d-i8Xnw',
    appId: '1:737126990757:web:978ac8b4dac8461f421e4c',
    messagingSenderId: '737126990757',
    projectId: 'my-goal-mate',
    authDomain: 'my-goal-mate.firebaseapp.com',
    storageBucket: 'my-goal-mate.appspot.com',
  );
}
